### ISSUE TITLE
Balls frozen on board

### ISSUE THREAD

**Issue by phet-steele** [phetsims/plinko-probability#90] opened 2016-09-19 18:24 UTC
Easiest setup to repro:
1. Lab screen, 26 rows, 0.5 probability.
2. Make sure the hopper is in Ball mode and you have continuous play mode selected.
3. Press play, let the balls drop for a few seconds.
4. Press pause, and while balls are still on the board, change the probability.

The balls will freeze in place. Further interaction (erasing, changing # of row, pressing play, etc.) will properly remove the balls

<img width="1387" alt="screen shot 2016-09-19 at 12 18 49 pm" src="https://cloud.githubusercontent.com/assets/5863899/18643809/f1c15bb8-7e63-11e6-9d81-1f93f3af5cc4.png">

Seen on Mac OSX 10.11.6 Chrome & iPad Air 2 iOS 10.0.1. For phetsims/tasks/issues/702.
Name: ‪Plinko Probability‬
URL: http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.0-rc.1/plinko-probability_en.html
Version: 1.0.0-rc.1 2016-09-16 19:30:26 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
Language: en-US
Window: 1388x1000
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"e0192608","branch":"HEAD"},"babel":{"sha":"c041de05","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"HEAD"},"chipper":{"sha":"07058555","branch":"HEAD"},"dot":{"sha":"39436598","branch":"HEAD"},"joist":{"sha":"b513b5ee","branch":"HEAD"},"kite":{"sha":"73302899","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"83ea84c8","branch":"HEAD"},"plinko-probability":{"sha":"3a105d26","branch":"HEAD"},"query-string-machine":{"sha":"05231e54","branch":"HEAD"},"scenery":{"sha":"e78ee413","branch":"HEAD"},"scenery-phet":{"sha":"f0fc9ae8","branch":"HEAD"},"sherpa":{"sha":"bcc28cd6","branch":"HEAD"},"sun":{"sha":"f2bd9d60","branch":"HEAD"},"tandem":{"sha":"d369b847","branch":"HEAD"},"vibe":{"sha":"b422db9c","branch":"HEAD"}}

**Comment by pixelzoom** [comment] 2016-09-19 18:53
This is due to yet-another missing call to `BallNodes.invalidatePaint`.  The root cause is sloppiness and redundancy in the model's `reset` and `erase` functions.  I was trying not to touch that stuff, but I will now bite the bullet and clean it up.

**Comment by pixelzoom** [comment] 2016-09-19 19:24
This issue is fixed in master and 1.0 branches.  This will need to be tested in another RC version.  In the meantime, @phet-steele you may verify in [1.0.0-dev.19](http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.0-dev.19/plinko-probability_en.html).

**Comment by phet-steele** [comment] 2016-09-19 20:16
This looks good, @pixelzoom

**Comment by pixelzoom** [comment] 2016-09-19 21:14
Great, closing.  We'll revisit in the next RC, and can reopen if there's a problem.

**Closed by pixelzoom** 2016-09-19 21:14 UTC
Labels: status:fixed-pending-testing, type:bug
